name: notifications_utils
description: A Flutter package to get delivered notifications from the notification center on Android, iOS and MacOS and cancel them.
version: 0.1.1
repository: https://github.com/Maksimka101/notifications_utils

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.1.3

flutter:
  plugin:
    platforms:
      android:
        package: com.zemlyanikin_maksim.notifications_utils
        pluginClass: NotificationsUtilsPlugin
      ios:
        pluginClass: NotificationsUtilsPlugin
      macos:
        pluginClass: NotificationsUtilsPlugin
